function doAll() {
    firebase.auth().onAuthStateChanged(user => {
        if (user) {
            getBookmarks(user)
        } else {
            console.log("No user is signed in");
        }
    });
}
doAll();

function getBookmarks(user) {
    db.collection("users").doc(user.uid).get()
        .then(userDoc => {
            var bookmarks = userDoc.data().bookmarks;
            console.log(bookmarks);

            let newcardTemplate = document.getElementById("ClinicCardTemplate2");
						// Iterate through the ARRAY of bookmarked favourites (document ID's)
            bookmarks.forEach(savedClinics => {
                console.log(savedClinics);
                db.collection("clinics").doc(savedClinics).get().then(doc => {
                    var clinicName = doc.data().clinicName;
                    var clinicAddress = doc.data().address;
                    var clinicCode = doc.data().code;
                    var docID = doc.id;  //this is the autogenerated ID of the document
                    
                    //clone the new card
                    let newcard = newcardTemplate.content.cloneNode(true);
    
                    //update to display clinicName, address, rating, hours, walkin_availibility, wait_time_minutes, last_updated
                    newcard.querySelector('#clinicName').innerHTML =
                        doc.data().clinicName + "<br>" +
                        doc.data().address + "<br>" 
                        newcard.querySelector('a').href = "clinic_profile_page.html?docID=" + docID;

                    ClinicCardGroup.appendChild(newcard);
                })
            });
        })
}

