//----------------------------------------------------------
// This function is the only function that's called.
// This strategy gives us better control of the page.
//----------------------------------------------------------
function doAll() {
    firebase.auth().onAuthStateChanged(user => {
        if (user) {
            getBookmarks(user)
        } else {
            console.log("No user is signed in");
        }
    });
}
doAll();



//----------------------------------------------------------
// This function takes input param User's Firestore document pointer
// and retrieves the "saved" array (of bookmarks) 
// and dynamically displays them in the gallery
//----------------------------------------------------------
function getBookmarks(user) {
    db.collection("users").doc(user.uid).get()
        .then(userDoc => {

					  // Get the Array of bookmarks
            var bookmarks = userDoc.data().bookmarks;
            console.log(bookmarks);
						
						// Get pointer the new card template
            let newcardTemplate = document.getElementById("ClinicCardTemplate2");
						// Iterate through the ARRAY of bookmarked favourites (document ID's)
            bookmarks.forEach(thisHikeID => {
                console.log(thisHikeID);
                db.collection("clinics").doc(thisHikeID).get().then(doc => {
                    var clinicName = doc.data().clinicName;
                    var clinicAddress = doc.data().address;
                    var clinicHours = doc.data().hours;
                    var rating = doc.data().rating; 
                    var clinicWaitTime = doc.data().wait_time_minutes;
                    var clinicWalkin = doc.data().walkin_availibility;
                    var clinicCode = doc.data().code;
                    var docID = doc.id;  //this is the autogenerated ID of the document
                    
                    //clone the new card
                    let newcard = newcardTemplate.content.cloneNode(true);

                    //update title and some pertinant information
                    newcard.querySelector('#clinicName').innerHTML = clinicName;
                    newcard.querySelector('#clinicAddress').innerHTML = clinicAddress;
                    newcard.querySelector('#clinic-rating').innerHTML = rating;
                    newcard.querySelector('.clinic-img').src = `../images/${clinicCode}.jpg`;
                    newcard.querySelector('#clinic-hours').innerHTML = clinicHours;
                    newcard.querySelector('#clinic-walkin').innerHTML = clinicWaitTime;
                    newcard.querySelector('#clinic-waittime').innerHTML = clinicWalkin;
                    newcard.querySelector('.clinic-img').href = "saved.html?docID="+docID;
    
                    //update to display clinicName, address, rating, hours, walkin_availibility, wait_time_minutes, last_updated
                    newcard.querySelector('#clinicName').innerHTML =
                        "clinicName: " + doc.data().clinicName + "<br>" +
                        "address: " + doc.data().address + "<br>" +
                        "rating: " + doc.data().rating + "<br>" +
                        "hours: " + doc.data().hours + "<br>" +
                        "walkin_availability: " + doc.data().walkin_availability + "<br>" +
                        "wait_time_minutes: " + doc.data().wait_time_minutes +

										//Finally, attach this new card to the gallery
                    ClinicCardGroup.appendChild(newcard);
                })
            });
        })
}